name: Build & Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Check out the repository's code

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1  # Log in to ECR using AWS credentials
        with:
          region: us-east-1  # Specify the AWS region

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .      # Build the image with the repository name (from secrets)

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

